# Nympy

In [1]:
import numpy as np

# Завдання
## 1. Створюэмо двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [2]:
size = 11
size_x = size
size_y = size

1.2. Створити нульовий масив заданого розміру

In [3]:
masiv = np.zeros((size_x,size_y))

1.3 Надрукувати створений масив

In [4]:
print(f'masiv =>\n{masiv} ')

masiv =>
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 


1.4 Змінити діагоналі за допомогою двох циклів

1.5 Вивести створений масив

In [5]:
masiv = np.zeros((size,size))
for i in range(size_x):
	for j in range(size_y):
		if ((size-1-i == j) or (i==j)):
			masiv[i][j] = 1
		else:
			masiv[i][j] = 0
            
print(f'masiv =>\n{masiv}')

masiv =>
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Горизонтальний градієнт

## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).


In [6]:
import cv2

2.1 Створити нульовий масив розміром 255х255

In [7]:
size = 255
horizontal_gradient_right = np.zeros((size,size))

2.2 Визначити розміри масиву

In [8]:
width = horizontal_gradient_right.shape[1]
height = horizontal_gradient_right.shape[0]

2.3 Поелементно змінити яскравості кожного пікселя

2.4 Записати зображення засабами OpenCV

In [9]:
horizontal_gradient_right = np.zeros((size,size))
for i in range(height):
    for j in range(width):
        horizontal_gradient_right[i][j] = j
        
cv2.imwrite('labs\lab1\horizontal_gradient_right.jpg', horizontal_gradient_right)
print(horizontal_gradient_right)


[[  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]
 ...
 [  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]]


2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [10]:
horizontal_gradient_left = np.zeros((size,size))
max_value = 255
for i in range(height):
    for j in range(width):
        horizontal_gradient_left[i][j] = max_value - j
        
cv2.imwrite('labs\lab1\horizontal_gradient_left.jpg', horizontal_gradient_left)
print(horizontal_gradient_left)


[[255. 254. 253. ...   3.   2.   1.]
 [255. 254. 253. ...   3.   2.   1.]
 [255. 254. 253. ...   3.   2.   1.]
 ...
 [255. 254. 253. ...   3.   2.   1.]
 [255. 254. 253. ...   3.   2.   1.]
 [255. 254. 253. ...   3.   2.   1.]]


### Вертикальний градієнт

In [11]:
vertical_gradient_down = np.zeros((size,size))
for i in range(height):
    for j in range(width):
        vertical_gradient_down[i][j] = i  
        
cv2.imwrite('labs\lab1\ vertical_gradient_down.jpg', vertical_gradient_down)
print(vertical_gradient_down)


[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   1.   1. ...   1.   1.   1.]
 [  2.   2.   2. ...   2.   2.   2.]
 ...
 [252. 252. 252. ... 252. 252. 252.]
 [253. 253. 253. ... 253. 253. 253.]
 [254. 254. 254. ... 254. 254. 254.]]


2.10 Аналогічно створити горизонтальний градієнт в інший бік

In [12]:
vertical_gradient_up = np.zeros((size,size))
max_value = 255
for i in range(height):
    for j in range(width):
        vertical_gradient_up[i][j] = max_value - i
        
cv2.imwrite('labs\lab1\ vertical_gradient_up.jpg', vertical_gradient_up)
print(vertical_gradient_up)


[[255. 255. 255. ... 255. 255. 255.]
 [254. 254. 254. ... 254. 254. 254.]
 [253. 253. 253. ... 253. 253. 253.]
 ...
 [  3.   3.   3. ...   3.   3.   3.]
 [  2.   2.   2. ...   2.   2.   2.]
 [  1.   1.   1. ...   1.   1.   1.]]
